Tue Oct 17 16:15:18 BST 2017 Thread[main,5,main] Cleanup action starting
java.sql.SQLException: Database 'TillEmbedded' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.github.davidg95.JTill.jtillserver.DBConnect.getNewConnection(DBConnect.java:330)
	at io.github.davidg95.JTill.jtillserver.DBConnect.updates(DBConnect.java:143)
	at io.github.davidg95.JTill.jtillserver.DBConnect.connect(DBConnect.java:139)
	at io.github.davidg95.JTill.jtillserver.GUI.databaseLogin(GUI.java:273)
	at io.github.davidg95.JTill.jtillserver.TillServer.start(TillServer.java:102)
	at io.github.davidg95.JTill.jtillserver.TillServer.main(TillServer.java:71)
Caused by: java.sql.SQLException: Database 'TillEmbedded' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 20 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'TillEmbedded' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.github.davidg95.JTill.jtillserver.DBConnect.getNewConnection(DBConnect.java:330)
	at io.github.davidg95.JTill.jtillserver.DBConnect.updates(DBConnect.java:143)
	at io.github.davidg95.JTill.jtillserver.DBConnect.connect(DBConnect.java:139)
	at io.github.davidg95.JTill.jtillserver.GUI.databaseLogin(GUI.java:273)
	at io.github.davidg95.JTill.jtillserver.TillServer.start(TillServer.java:102)
	at io.github.davidg95.JTill.jtillserver.TillServer.main(TillServer.java:71)
============= end nested exception, level (1) ===========
Cleanup action completed
Tue Oct 17 16:15:18 BST 2017 Thread[main,5,main] Cleanup action starting
java.sql.SQLException: Database 'TillEmbedded' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.github.davidg95.JTill.jtillserver.DBConnect.getNewConnection(DBConnect.java:330)
	at io.github.davidg95.JTill.jtillserver.DBConnect.getStaffCount(DBConnect.java:1565)
	at io.github.davidg95.JTill.jtillserver.GUI.databaseLogin(GUI.java:274)
	at io.github.davidg95.JTill.jtillserver.TillServer.start(TillServer.java:102)
	at io.github.davidg95.JTill.jtillserver.TillServer.main(TillServer.java:71)
Caused by: java.sql.SQLException: Database 'TillEmbedded' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'TillEmbedded' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.github.davidg95.JTill.jtillserver.DBConnect.getNewConnection(DBConnect.java:330)
	at io.github.davidg95.JTill.jtillserver.DBConnect.getStaffCount(DBConnect.java:1565)
	at io.github.davidg95.JTill.jtillserver.GUI.databaseLogin(GUI.java:274)
	at io.github.davidg95.JTill.jtillserver.TillServer.start(TillServer.java:102)
	at io.github.davidg95.JTill.jtillserver.TillServer.main(TillServer.java:71)
============= end nested exception, level (1) ===========
Cleanup action completed
----------------------------------------------------------------
Tue Oct 17 16:15:18 BST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.10.1.3 - (1557168): instance a816c00e-015f-2ae7-3bf5-0000060ceeb0 
on database directory C:\Users\David\Honors Project\Till\JTillServer\TillEmbedded with class loader sun.misc.Launcher$AppClassLoader@677327b6 
Loaded from file:/C:/Users/David/Honors%20Project/Till/JTillServer/derby/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_121-b13
user.dir=C:\Users\David\Honors Project\Till\JTillServer
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
